language: ruby
cache:
  - npm
  - bundler
rvm:
  - 2.4
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - cd ${FOREMAN_PLUGIN_NAME}
  - bundle install --jobs=3 --retry=3
  - npm install eslint
  - cd ../foreman
  - echo "gemspec :path => '../${FOREMAN_PLUGIN_NAME}'" > bundler.d/${FOREMAN_PLUGIN_NAME}.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - ln -s database.yml.example config/database.yml
  - bundle install --jobs=3 --retry=3 --without journald development postgresql mysql2 console journald
  - npm install
  - bundle exec rake webpack:compile
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - cd ../${FOREMAN_PLUGIN_NAME}
  - # bundle exec rubocop
  - # node ./node_modules/.bin/eslint . app/**/*.js
  - cd ../foreman
  - bundle exec rake test:${FOREMAN_PLUGIN_NAME}
  - bundle exec rake "plugin:assets:precompile[${FOREMAN_PLUGIN_NAME}]" RAILS_ENV=production
env:
  global:
    - TESTOPTS=-v
    - FOREMAN_PLUGIN_NAME=foreman_azure_rm
  matrix:
    - FOREMAN_CORE_BRANCH=develop
addons:
  apt:
    packages:
    - nodejs
    - git
    - libsqlite3-dev
    - zlib1g-dev
    - libvirt-dev
